---
title: "Social Capital"
author: "Tejas Mundhe"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggthemes)
library(plotly)
library(patchwork)
```

```{r grap_data}
raw_data <- read_rds("ec.rds")
# glimpse(raw_data)
```

```{r clean_data}
clean_data <- raw_data |>
  mutate(state = str_remove(county_name, ".*, ")) |>
  drop_na() |>
  group_by(state) |>
  summarize(state_pop = sum(pop2018), avg_ec = mean(ec_county))
# summary(clean_data)
```

```{r plot, fig.align='center'}
ec_plot <- clean_data |>
  ggplot(mapping = aes(x = state_pop, y = avg_ec)) +
  geom_point(shape = 21, color = "steelblue") +
  geom_smooth(method = "loess", formula = y ~ x, se = FALSE, color = "pink", size = 1.5) +
  scale_x_log10(breaks = c(500000, 1000000, 3000000, 10000000, 40000000),
                labels = c("500,000", "1,000000", "3,000,000", "10,000,000", "40,000,000")) +
  labs(title = "Economic Connectedness by State Population",
       subtitle = "More populated states tend to have a lower average economic connectedness",
       x = "State Population",
       y = "Economic Connectedness",
       caption = "Source: New York Times") +
  theme_clean()

ggplotly(ec_plot)
```


<br>
<br>

```{r table1, warning = FALSE}
library(gt)
clean_data |>
  select(state, state_pop, avg_ec) |>
  mutate(state_pop = as.numeric(state_pop)) |>
  arrange(desc(state_pop)) |>
  slice(1:8) |>
  gt() |>
  tab_header(title = "EC Scores for Top 8 Most Populated States") |>
  cols_label(state = "State", state_pop = "Population", avg_ec = "EC Score") |>
  data_color(columns = c(state_pop),
             colors = scales::col_numeric(palette = c(
        "yellow", "red", "purple"),
        domain = c(10000000, 40000000)))
```


<br>

```{r table2, warning = FALSE}
clean_data |>
  select(state, state_pop, avg_ec) |>
  mutate(state_pop = as.numeric(state_pop)) |>
  arrange(state_pop) |>
  slice(1:8) |>
  gt() |>
  tab_header(title = "EC Scores for Top 8 Least Populated States") |>
  cols_label(state = "State", state_pop = "Population", avg_ec = "EC Score") |>
  data_color(columns = c(state_pop),
             colors = scales::col_numeric(palette = c(
        "yellow", "red", "purple"),
        domain = c(550000, 1020000)))

```

